### ISSUE TITLE
Line without a Redaction

### ISSUE THREAD

**Issue by nathanscain** [cegme/cs5293sp22#145]
@siddhardha-maguluri Your line 3460 doesn't have a redaction in it. I've added a check for this in my pipeline, but would be good to fix.

**Comment by siddhardha-maguluri** [comment]
created #151 for this issue.

**Comment by siddhardha-maguluri** [comment]
Resolved the issue in #165. kindly verify and close this.

**Comment by cegme** [comment]
Verified. Thanks
