### ISSUE TITLE
Lines combining into single row using pd.read_csv("unredactor.tsv", sep='\t')

### ISSUE THREAD

**Issue by JDewberry** [cegme/cs5293sp22#160]
I am not entirely sure what is causing the issue, but lines 121-141(at least) are combined the last column of  a single row in the data frame created.

**Comment by cegme** [comment]
Is it actually 121?  Can you verify the line outside of pandas?
It could be a quotation issue...

**Comment by JDewberry** [comment]
here is the line:
wboncal	training	Andy Goldsworthy	"I considered ████████████████ one of the great contemporary artists.
and i think you are right and that it is a quotation issue

**Comment by cegme** [comment]
Try removing that quote manually and see if you run into the same problem.

**Comment by JDewberry** [comment]
removing the quote fixes the issue.

**Comment by cegme** [comment]
You can remove it and add a pull request. This is on my list to do tomorrow morning.
You should also add the parameter `quoting=csv.QUOTE_NONE`

**Comment by cegme** [comment]
I'll use vim to get rid of hte full quotes 

```
:%s/\t"\(.*\)"/\t\1/
```

Then the double quotes and make them single.

```
:s%/""/"/
```

**Comment by cegme** [comment]
This is related to Issue #103 closing,
